name: Rebuild Eleventy Site

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual rebuild trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Eleventy Build
        run: npm run build

