name: Rebuild Eleventy Site

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual rebuild trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Eleventy
        run: npx @11ty/eleventy

      - name: Deploy (Optional)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated Eleventy Build [skip ci]" || exit 0
          git push

      - name: Deploy to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_TOKEN }}
        run: |
          neocities push _site --key $NEOCITIES_API_KEY

